export const contacts : any[] = [
  {
    "id": 1,
    "name": "Alice Johnson",
    "email": "alice.johnson@example.com",
    "phone": "123-456-7890",
    "gender": "Female",
    "dob": "1990-04-15",
    "religion": "Christianity",
    "anniversary": "2015-06-20",
    "city": "Los Angeles",
    "state": "California",
    "address": "123 Main St, Los Angeles, CA 90001",
    "leadSource": "Social Media",
    "leadStage": "Interested",
    "assignTo": "John Smith",
    "products": []
  },
  {
    "id": 2,
    "name": "Bob Williams",
    "email": "bob.williams@example.com",
    "phone": "987-654-3210",
    "gender": "Male",
    "dob": "1985-02-10",
    "religion": "Hinduism",
    "anniversary": "2012-11-05",
    "city": "New York",
    "state": "New York",
    "address": "456 Elm St, New York, NY 10001",
    "leadSource": "Referral",
    "leadStage": "New",
    "assignTo": "Jane Doe",
    "products": []
  },
  {
    "id": 3,
    "name": "Charlie Davis",
    "email": "charlie.davis@example.com",
    "phone": "555-123-4567",
    "gender": "Male",
    "dob": "1992-08-25",
    "religion": "Islam",
    "anniversary": "2020-05-15",
    "city": "Chicago",
    "state": "Illinois",
    "address": "789 Oak St, Chicago, IL 60601",
    "leadSource": "Website",
    "leadStage": "Engaged",
    "assignTo": "Emily Clark",
    "products": []
  },
  {
    "id": 4,
    "name": "Diana Evans",
    "email": "diana.evans@example.com",
    "phone": "222-333-4444",
    "gender": "Female",
    "dob": "1988-12-05",
    "religion": "Buddhism",
    "anniversary": "2018-09-30",
    "city": "Houston",
    "state": "Texas",
    "address": "101 Pine St, Houston, TX 77001",
    "leadSource": "Event",
    "leadStage": "Converted",
    "assignTo": "Mark Lee",
    "products": []
  },
  {
    "id": 5,
    "name": "Evelyn Scott",
    "email": "evelyn.scott@example.com",
    "phone": "777-888-9999",
    "gender": "Female",
    "dob": "1995-07-10",
    "religion": "Judaism",
    "anniversary": "2023-03-10",
    "city": "Phoenix",
    "state": "Arizona",
    "address": "202 Maple St, Phoenix, AZ 85001",
    "leadSource": "Advertisement",
    "leadStage": "Follow Up",
    "assignTo": "Rachel Green",
    "products": []
  },
  {
    "id": 6,
    "name": "Frank Harris",
    "email": "frank.harris@example.com",
    "phone": "321-654-9870",
    "gender": "Male",
    "dob": "1982-03-17",
    "religion": "Atheism",
    "anniversary": "2010-12-01",
    "city": "Philadelphia",
    "state": "Pennsylvania",
    "address": "303 Birch St, Philadelphia, PA 19019",
    "leadSource": "Direct Contact",
    "leadStage": "Interested",
    "assignTo": "Chris Redfield",
    "products": []
  },
  {
    "id": 7,
    "name": "Grace White",
    "email": "grace.white@example.com",
    "phone": "654-321-7890",
    "gender": "Female",
    "dob": "1993-10-22",
    "religion": "Christianity",
    "anniversary": "2017-04-18",
    "city": "San Antonio",
    "state": "Texas",
    "address": "404 Cedar St, San Antonio, TX 78201",
    "leadSource": "Social Media",
    "leadStage": "Engaged",
    "assignTo": "Nick Fury",
    "products": []
  },
  {
    "id": 8,
    "name": "Henry Adams",
    "email": "henry.adams@example.com",
    "phone": "888-777-6666",
    "gender": "Male",
    "dob": "1978-06-02",
    "religion": "Christianity",
    "anniversary": "2005-08-12",
    "city": "San Diego",
    "state": "California",
    "address": "505 Redwood St, San Diego, CA 92101",
    "leadSource": "Referral",
    "leadStage": "Converted",
    "assignTo": "Tony Stark",
    "products": []
  },
  {
    "id": 9,
    "name": "Ivy Moore",
    "email": "ivy.moore@example.com",
    "phone": "444-555-6666",
    "gender": "Female",
    "dob": "1991-01-15",
    "religion": "Hinduism",
    "anniversary": "2021-10-25",
    "city": "Dallas",
    "state": "Texas",
    "address": "606 Palm St, Dallas, TX 75201",
    "leadSource": "Event",
    "leadStage": "New",
    "assignTo": "Steve Rogers",
    "products": []
  },
  {
    "id": 10,
    "name": "Jack Cooper",
    "email": "jack.cooper@example.com",
    "phone": "999-111-2222",
    "gender": "Male",
    "dob": "1980-11-11",
    "religion": "Islam",
    "anniversary": "2008-07-14",
    "city": "San Francisco",
    "state": "California",
    "address": "707 Sequoia St, San Francisco, CA 94101",
    "leadSource": "Website",
    "leadStage": "Follow Up",
    "assignTo": "Natasha Romanoff",
    "products": []
  },
  {
    "id": 11,
    "name": "Karen Taylor",
    "email": "karen.taylor@example.com",
    "phone": "123-987-6543",
    "gender": "Female",
    "dob": "1987-03-19",
    "religion": "Christianity",
    "anniversary": "2016-05-21",
    "city": "Austin",
    "state": "Texas",
    "address": "808 Walnut St, Austin, TX 73301",
    "leadSource": "Advertisement",
    "leadStage": "Engaged",
    "assignTo": "Bruce Wayne",
    "products": []
  },
  {
    "id": 12,
    "name": "Leo Martinez",
    "email": "leo.martinez@example.com",
    "phone": "888-333-7777",
    "gender": "Male",
    "dob": "1994-09-30",
    "religion": "Christianity",
    "anniversary": "2019-11-03",
    "city": "Miami",
    "state": "Florida",
    "address": "909 Cypress St, Miami, FL 33101",
    "leadSource": "Referral",
    "leadStage": "Converted",
    "assignTo": "Clark Kent",
    "products": []
  },
  {
    "id": 13,
    "name": "Megan Parker",
    "email": "megan.parker@example.com",
    "phone": "555-888-4444",
    "gender": "Female",
    "dob": "1998-12-12",
    "religion": "Buddhism",
    "anniversary": "2022-07-22",
    "city": "Seattle",
    "state": "Washington",
    "address": "707 Spruce St, Seattle, WA 98101",
    "leadSource": "Social Media",
    "leadStage": "Interested",
    "assignTo": "Diana Prince",
    "products": []
  },
  {
    "id": 14,
    "name": "Nathan Hall",
    "email": "nathan.hall@example.com",
    "phone": "333-444-5555",
    "gender": "Male",
    "dob": "1975-11-05",
    "religion": "Hinduism",
    "anniversary": "2001-09-15",
    "city": "Denver",
    "state": "Colorado",
    "address": "202 Cherry St, Denver, CO 80201",
    "leadSource": "Event",
    "leadStage": "Follow Up",
    "assignTo": "Peter Parker",
    "products": []
  },
  {
    "id": 15,
    "name": "Olivia Carter",
    "email": "olivia.carter@example.com",
    "phone": "666-777-8888",
    "gender": "Female",
    "dob": "1993-04-14",
    "religion": "Islam",
    "anniversary": "2017-10-05",
    "city": "Portland",
    "state": "Oregon",
    "address": "505 Ash St, Portland, OR 97201",
    "leadSource": "Direct Contact",
    "leadStage": "New",
    "assignTo": "Bruce Banner",
    "products": []
  },
  {
    "id": 16,
    "name": "Paul Baker",
    "email": "paul.baker@example.com",
    "phone": "222-111-3333",
    "gender": "Male",
    "dob": "1989-07-08",
    "religion": "Christianity",
    "anniversary": "2014-08-22",
    "city": "Boston",
    "state": "Massachusetts",
    "address": "303 Poplar St, Boston, MA 02101",
    "leadSource": "Website",
    "leadStage": "Interested",
    "assignTo": "Steve Rogers",
    "products": []
  },
  {
    "id": 17,
    "name": "Quinn Rivera",
    "email": "quinn.rivera@example.com",
    "phone": "444-555-6666",
    "gender": "Female",
    "dob": "1984-01-11",
    "religion": "Atheism",
    "anniversary": "2009-06-15",
    "city": "Las Vegas",
    "state": "Nevada",
    "address": "707 Oak St, Las Vegas, NV 89101",
    "leadSource": "Event",
    "leadStage": "Converted",
    "assignTo": "Natasha Romanoff",
    "products": []
  },
  {
    "id": 18,
    "name": "Ryan Cooper",
    "email": "ryan.cooper@example.com",
    "phone": "999-000-1111",
    "gender": "Male",
    "dob": "1980-03-10",
    "religion": "Judaism",
    "anniversary": "2010-04-01",
    "city": "San Jose",
    "state": "California",
    "address": "606 Fir St, San Jose, CA 95101",
    "leadSource": "Advertisement",
    "leadStage": "Engaged",
    "assignTo": "Tony Stark",
    "products": []
  },
  {
    "id": 19,
    "name": "Sophia Kelly",
    "email": "sophia.kelly@example.com",
    "phone": "888-999-0000",
    "gender": "Female",
    "dob": "1990-05-20",
    "religion": "Christianity",
    "anniversary": "2018-02-12",
    "city": "Charlotte",
    "state": "North Carolina",
    "address": "909 Maple St, Charlotte, NC 28201",
    "leadSource": "Referral",
    "leadStage": "Follow Up",
    "assignTo": "Peter Parker",
    "products": []
  },
  {
    "id": 20,
    "name": "Thomas King",
    "email": "thomas.king@example.com",
    "phone": "111-222-3333",
    "gender": "Male",
    "dob": "1983-09-25",
    "religion": "Christianity",
    "anniversary": "2008-11-18",
    "city": "Memphis",
    "state": "Tennessee",
    "address": "202 Walnut St, Memphis, TN 38101",
    "leadSource": "Social Media",
    "leadStage": "New",
    "assignTo": "Bruce Wayne",
    "products": []
  }
]